【問題1】行列積を手計算する

$$
    \boldsymbol{A} =
        \left[\begin{array}{ccc}
            -1 &  2  &  3 \\
            4  & -5  &  6 \\
            7  &  8  & -9 \\
        \end{array}\right] \quad
$$


$$
    \boldsymbol{B} =
        \left[\begin{array}{ccc}
            0  &  2  &  1 \\
            0  &  2  & -8 \\
            2  &  9  & -1 \\
        \end{array}\right] \quad
$$

(AB)<sub/>11</sub> = A<sub/>11</sub>B<sub/>11</sub> + A<sub/>12</sub>B<sub/>21</sub> + A<sub/>13</sub>B<sub/>31</sub>

$$
    \boldsymbol{A}{B} =
        \left[\begin{array}{ccc}
            (-1)*(0)+(2)*(0)+(3)*(2)  &  (-1)*(2)+(2)*(2)+(3)*(9)  &  (-1)*(1)+(2)*(-8)+(3)*(-1) \\
            (4)*(0)+(-5)*(0)+(6)*(2)  &  (4)*(2)+(-5)*(2)+(6)*(9)  &  (4)*(1)+(-5)*(-8)+(6)*(-1) \\
            (7)*(0)+(8)*(0)+(-9)*(2)  &  (7)*(2)+(8)*(2)+(-9)*(9)  &  (7)*(1)+(8)*(-8)+(-9)*(-1) \\
        \end{array}\right] \quad
$$
  
$$
    \boldsymbol{A}{B} =
        \left[\begin{array}{ccc}
             6  &   29  &  -20 \\
            12  &   52  &   38 \\
           -18  &  -51  &  -48 \\
        \end{array}\right] \quad
$$



【問題2】NumPyの関数による計算

In [8]:
import numpy as np
a = np.array([[-1, 2, 3],
              [ 4,-5, 6],
              [ 7, 8,-9]])
b = np.array([[ 0, 2, 1],
             [ 0, 2,-8],
             [ 2, 9,-1]])
ab1 = np.matmul(a,b)
print(ab1)
#ab2 = np.dot(a,b)
#print(ab2)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装

In [38]:
#関数内のfor文では、Ａの行とＢの列を固定、Ａの列とＢの行を変化させる。ループさせて合計する。

def obtain_element(column,row,a_y,b_y,ab_size):
    sum = 0
    for i in range(ab_size):
        sum += a_y[column][i]*b_y[i][row]
    return sum

# print(a.shape[0])
print(obtain_element(0,0,a,b,3))

6


【問題4】行列積を行う関数の作成

＜ＭＥＭＯ＞
  引き数を２つの行列とする関数「obtain_matrix_prodact」。 
  その内部で問題３での関数「obtain_element」を呼び出している。  
　obtain_elementの引数は、columnとrowに対応するループ変数ⅰとｊ、さらに「obtain_matrix_prodact」の引き数である２つの行列、Ａの次元としている。  
　obtain_matrix_productは、行列積を返す。  
  obtain_elementは、 行列積の各要素を返している。


In [46]:
def obtain_matrix_product(a_x,b_x):
#返り値とする行列積を定義している。
    matrix_product = np.array(range(a_x.shape[0]*b_x.shape[1]))
    matrix_product = matrix_product.reshape(a_x.shape[0], b_x.shape[1])
#２重ループでobtain_elementを呼び出し、各要素を演算。
    for i in range(a_x.shape[0]):
        for j in range(b_x.shape[1]):
            matrix_product[i][j] = obtain_element(i, j, a_x, b_x, a_x.shape[1])
    return matrix_product

a5 = np.array([[-1, 2, 3],
              [ 4,-5, 6],
              [ 7, 8,-9]])
b5 = np.array([[ 0, 2, 1],
             [ 0, 2,-8],
             [ 2, 9,-1]])

print(obtain_matrix_product(a5, b5))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題5】計算が定義されない入力を判定する。

In [ ]:
２行目から４行目を加筆。

In [61]:
def obtain_matrix_product(a_x,b_x):
# Ａの列成分とＢの行成分の要素数が等しくなければ行列積は求められない。
    if a_x.shape[1] != b_x.shape[0]:
        return print("行列積を求められません")
#返り値とする行列積を定義している。行列積はＡの行数とＢの列数となる。
    matrix_product = np.array(range(a_x.shape[0]*b_x.shape[1]))
    matrix_product = matrix_product.reshape(a_x.shape[0], b_x.shape[1])
#２重ループでobtain_elementを呼び出し、各要素を演算。
    for i in range(a_x.shape[0]):
        for j in range(b_x.shape[1]):
            matrix_product[i][j] = obtain_element(i, j, a_x, b_x, a_x.shape[1])
    return matrix_product

a5 = np.array([[-1, 2, 3],
              [ 4,-5, 6],
              [ 7, 8,-9]])
b5 = np.array([[ 0, 2, 1],
             [ 0, 2,-8],
             [ 2, 9,-1]])

obtain_matrix_product(a5, b5)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

【問題6】転置

＜ＭＥＭＯ＞転置をする意義がよくわからなかった。行列積ではなく行列式を求める？

In [111]:
import numpy as np
a10 = np.array([[-1, 2, 3],
              [ 4,-5, 6],
              [ 7, 8,-9]])
b10 = np.array([[ 0, 2, 1],
             [ 0, 2,-8],
             [ 2, 9,-1]])

#b10を転置
b10 = np.transpose(b10)

#解となる行列積の定義
ab = np.array(range(9))
ab = ab.reshape(3,3)

for i in range(3):
    for j in range(3):
        #転置をしているので、ＡのＩ行目とＢのＪ行目の内積を取る。
        ab[i][j] = np.dot(a10[i,:],b10[j,:])
ab

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])