## 【問題1】これまで利用してきたクラスの列挙

Pandas : DataFrame,Series  
matplotlab: Figure,Axes,Patch,Ecllips  
scikit-learn: LinearRegression, SVR  


## 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

 メソッド：  
 ・pandasのDataFrameオブジェクトにおける、head(), info(), describe(), keys()   
 ・sklearn.linear_modelのLinearRegressionにおける、fit(), predict(), score()    
   
 インスタンス変数：  
 ・sklearn.linear_modelのLinearRegressionにおける、rank_, coef_  
 ・numpyの、dtype, size  
 ・pandasのDataFrameの、columns, dtypes, style, iloc  
 
 pandasの公式ドキュメントではilocやlicはインスタンス変数だが、メソッドのようにも思えてしまう。

##  【問題3】標準化クラスをスクラッチで作成

In [35]:
class ScratchStandardScaler():
    """
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    mean_ = []
    std_ = []

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """     
        self.mean_ = np.average(X,axis=0)
        self.std_ = np.std(X,axis=0)

        pass

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = (X-self.mean_)/self.std_
        
        pass
        return X_scaled
    



In [36]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.std_))
X_std = scratch_scaler.transform(X)
print(X_std)


平均 : [4.86 3.31 1.45 0.22]
分散 : [0.2764055  0.29137605 0.10246951 0.07483315]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# 【問題４】四則演算を行うクラスの作成

In [59]:

class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value

        #valueが数値以外だった場合のエラー出力。
        if type(self.value) != int and type(self.value) != float:
            print("error")
        else:
            print("初期値{}が設定されました".format(self.value))
            
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    
    # 引き算
    def subt(self, value3):
        self.value -= value3
    # かけ算
    def accum(self, value4):
        self.value *= value4    
    # 割り算
    def div(self, value5):
        self.value /= value5
        
        
example = ExampleClass(36)
print("value : {}".format(example.value))
example.add(5)
print("value : {}".format(example.value))
example.subt(3)
print("value : {}".format(example.value))
example.accum(3)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))


初期値36が設定されました
value : 36
value : 41
value : 38
value : 114
value : 38.0
